export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const LOAD_PROJECT_SUCCESS = 'LOAD_PROJECT_SUCCESS'
